### ISSUE TITLE
Calling to_html to a node of paragraph causes an error

### ISSUE THREAD

**Issue by wakairo** [gjtorikian/commonmarker#327]
I tested the following code, and it seems that calling to_html to a node of paragraph causes an error.

## Code

```ruby
require 'commonmarker'

p RUBY_VERSION # => "3.2.3"
p Commonmarker::VERSION # => "2.0.1"

document = Commonmarker.parse("- a")
p document.first_child.type # => :list
p document.first_child.to_html # => "<ul>\n<li>a</li>\n</ul>\n"

document = Commonmarker.parse("ABC")
p document.first_child.type # => :paragraph
p document.first_child.to_html # An error occurs.
```

## Output of the code

```sh
$ ruby step_to_reproduce.rb
"3.2.3"
"2.0.1"
:list
"<ul>\n<li>a</li>\n</ul>\n"
:paragraph
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/comrak-0.30.0/src/html.rs:683:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/var/lib/gems/3.2.0/gems/commonmarker-2.0.1-x86_64-linux/lib/commonmarker/node.rb:47:in `node_to_html': called `Option::unwrap()` on a `None` value (fatal)
        from /var/lib/gems/3.2.0/gems/commonmarker-2.0.1-x86_64-linux/lib/commonmarker/node.rb:47:in `to_html'
        from step_to_reproduce.rb:12:in `<main>'
```

**Comment by gjtorikian** [comment]
Thanks for the report. I am ack'ing this, but I don't have time for a fix just yet!

**Comment by kivikakk** [comment]
Looks like Comrak's `html::render_paragraph` assumes a paragraph always has a parent — many of the formatters will assume this, expecting there will be at the very least a `Document` — but in this case `CommonmarkerNode::to_html` calls `comrak::format_html_with_plugins` on a `Paragraph` node directly.

We don't need to make that assumption, so it's easy to fix this case, but I haven't checked all the different node render functions. We'll probably want to do that systematically in Comrak so this kind of thing can't pop up all over.

**Comment by gjtorikian** [comment]
Ah, yeah, I used to have a branch where I had reached the same conclusion—but I still think the way I'm constructing ASTs is wrong, or at least, can be changed to conform to what comrak expects. Like, if memory serves, commonmarker is manually creating `AstNode` structures and chaining them together. I don't think it's impossible for this process to just first push a `Document` as a parent. 

From another perspective, this gem should never panic; I view that as an error in working with comrak's API, rather than a deficiency on comrak's assumptions!

**Comment by kivikakk** [comment]
I agree that the gem shouldn't panic! It's more that it's given me time to reflect and think — well, why _can't_ someone just format a paragraph if they want? In my view, Comrak should also avoid panicking, but there are plenty of ways to use it unsafely when manually constructing ASTs, and imo that's a bug.

It's a particularly bad kind because it's latent when you're constructing/manipulating the tree, only surfacing later when you happen to use a formatter that makes such an assumption.

So (again imo, open to being swayed), the way Commonmarker's constructing an AST _should_ be fine (and I've seen others do it with Comrak directly!), and Comrak should never panic when formatting, whatever the input.

**Comment by kivikakk** [comment]
A fix for this has been merged in Comrak, and will be part of its next release, and most likely Commonmarker's too! I'll close this issue when that comes to pass.

**Comment by kivikakk** [comment]
The fix for this went out with Comrak [v0.41.1](https://github.com/kivikakk/comrak/releases/tag/v0.41.1) on the weekend, now part of Commonmarker [v2.4.0](https://github.com/gjtorikian/commonmarker/releases/tag/v2.4.0). Thank you for the report!

```console
$ ruby step_to_reproduce.rb
"3.4.4"
"2.4.0"
:list
"<ul>\n<li>a</li>\n</ul>\n"
:paragraph
"<p>ABC</p>\n"
```
