### ISSUE TITLE
ruby-enum v0.7.1 breaks the gem

### ISSUE THREAD

**Issue by hmnhf** [gjtorikian/commonmarker#35]
Hi,

After doing a regular `bundle update`, because of https://github.com/dblock/ruby-enum/pull/16, I'm getting this error:
```
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'commonmarker'. (Bundler::GemRequireError)
Gem Load Error is: wrong constant name default
Backtrace for gem load error is:
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-enum-0.7.1/lib/ruby-enum/enum.rb:34:in `const_set'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-enum-0.7.1/lib/ruby-enum/enum.rb:34:in `define'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker/config.rb:8:in `<class:Parse>'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker/config.rb:5:in `<module:Config>'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker/config.rb:4:in `<module:CommonMarker>'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker/config.rb:2:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker.rb:3:in `require'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commonmarker-0.14.3/lib/commonmarker.rb:3:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
...
```

**Comment by kivikakk** [comment]
Ah. I'll pin `ruby-enum` at `0.5.0`, which is what my local `Gemfile.lock` is at, and re-release.

**Comment by kivikakk** [comment]
@hmnhf: this should be fixed in commonmarker-0.14.4! Could you please check this is all working for you now? There's also been an update to the latest cmark upstream as part of this.

**Comment by hmnhf** [comment]
@kivikakk It's all working again. Thanks!

**Comment by kivikakk** [comment]
Great! Thanks for getting back to us! ✨
